trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: SSH@0
  inputs:
    sshEndpoint: 'adventour-ssh-connection'
    runOptions: 'inline'
    inline: |
      cd /home/azureuser/adventour-backend
      git pull origin main
      docker-compose down
      docker-compose up -d --build
