version: "3.8"

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SQL_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

  sql-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: sqlinit
    depends_on:
      - db
    environment:
      SQL_PASSWORD: ${SQL_PASSWORD}
    restart: "no"

  api:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQL_CONNECTION_STRING=Server=mssql;Database=${DATABASE};User Id=${SQL_USER};Password=${SQL_PASSWORD}
      - TOMTOM_API_KEY=hxWDxSFNpJl86Y0yFIpnkO0zALaj2D9o
    volumes:
      - ./database:/database
    depends_on:
      - db
      - sql-init

  nginx:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: nginx_reverse_proxy
    ports:
      # - "80:80"
      - "8181:80"
    depends_on:
      - api

volumes:
  mssql_data:
